version: '3.8'

services:
  app:
    build: .
    container_name: moi-app-api
    working_dir: /src
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - PORT=3000
      - NODE_ENV=production
    command: ["npm", "run", "start"]
    volumes:
      - ./src:/src/src
      - ./tsconfig.json:/src/tsconfig.json
      - ./package.json:/src/package.json
      - ./package-lock.json:/src/package-lock.json