version: '3.8'

services:
  app:
    build: .
    container_name: moi-app-api
    working_dir: /src
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - PORT=3000
      - NODE_ENV=production
    command: ["node", "dist/index.js"]
