service: moi-app-api
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  memorySize: 512
  timeout: 10

functions:
  api:
    handler: dist/lambda.handler
    events:
      - httpApi: "*"
